#!/bin/sh
# Deploy dotfiles in a new system

echo "Untested, will not run"
exit 1

set -e

systems="macos linux illumos freebsd msys"

parse_error() {
  printf "Usage: ${0} <system> [-d]\n" 
  printf "Where system must be one of the following:\n"
  for system in $systems; do
    printf "$system "
  done
  printf "\n\n"
  printf "  -d: Dry-run. Only lists changes to be made.\n"
  exit 1
}

gen_bkpdir_name() {
  printf "${HOME}/.dotfilesbkp-$(date +%Y-%m-%d-%H:%M:%S)"
}

get_abs_path() {

}

run_cmd() {
  echo "$@"
  if ! [ $dry_run ]; then
    "$@"
  fi
}

link_item() {
  src="$1"
  dst="$2"
  bkp="$3"
  dst_path=$(dirname "$dst")

  if [ ! -d "$dst_path" ]; then
    run_cmd mkdir -p "$dst_path"
  fi  

  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    backup_item "$dst" "$bkp"
  fi

  if [ -L "$dst" ]; then
    run_cmd rm "$dst"
  fi

  run_cmd ln -s "$src" "$dst"
}

backup_item() {
  src="$1"
  dst_root="$2"
  dst="${dst_root}/${src#$HOME/}"
  dst_path=$(dirname "$dst")

  if [ ! -d "${dst_path}" ]; then
    run_cmd mkdir -p "${dst_path}"
  fi

  run_cmd mv "${src}" "${dst}"
}

bkppath=$(gen_bkpdir_name)

if [ $# -lt 1 ]; then
  parse_error
elif ! echo "$systems" | grep -qw "$1"; then
  parse_error
fi

if [ "$2" = "-d" ]; then
  dry_run=true
fi

if ! [ $dry_run ]; then
  printf "This script will link the dotfiles in this repository to your home \
directory, replacing your current configuration. Files that are replaced will \
be backed up to %s\n\nDo you wish to continue? (Y/n)" "${bkppath}"

  read proceed
  case "$proceed" in
    [Yy]*)
      ;;
    *)
      printf "Aborting\n"
      exit 0
      ;;
  esac
fi

cd $(dirname "$0")

install_subdirs="common $1"

for subdir in $install_subdirs; do
  dir="./${subdir}/home"
  for relsrc in "${dir}/*"; do
    src=$(get_abs_path "${relsrc}")

    item=$(basename "${src}")
    if [ "${item}" != "${item#_}" ]; then
      item=".${item#_}"
    fi
    dst="${HOME}/${item}"

    link_item "${src}" "${dst}" "${bkppath}"
  done
done

printf "\nCompleted configuration for %s\n" "${1}"
if [ $dry_run ]; then
  printf "The -d option was used, so no changes have been made to the filesystem\n"
fi
