#!/bin/sh
# Deploy dotfiles in a new system

set -e

systems="macos linux illumos freebsd msys"
shared_dirs="bin .config"

parse_error() {
  printf "Usage: ${0} <system> [-d]\n" 
  printf "Where system must be one of the following:\n"
  for l_pe_system in $systems; do
    printf "$l_pe_system "
  done
  printf "\n\n"
  printf "  -d: Dry-run. Only lists changes to be made.\n"
  exit 1
}

get_abs_path() {
  if [ -d "$1" ]; then
    (cd "$1" && pwd -P)
  else
    l_gp_dir=$(dirname "$1")
    l_gp_file=$(basename "$1")
    l_gp_abs_dir=$(cd "$l_gp_dir" && pwd -P)
    printf "${l_gp_abs_dir}/${l_gp_file}"
  fi
}

run_cmd() {
  echo "$@"
  if ! [ $dry_run ]; then
    "$@"
  fi
}

link_item() {
  l_li_src="$1"
  l_li_dst="$2"
  l_li_bkp="$3"
  l_li_dst_path=$(dirname "$l_li_dst")

  if [ ! -d "$l_li_dst_path" ]; then
    run_cmd mkdir -p "$l_li_dst_path"
  fi  

  if [ -e "$l_li_dst" ] && [ ! -L "$l_li_dst" ]; then
    backup_item "$l_li_dst" "$l_li_bkp"
  fi

  if [ -L "$l_li_dst" ]; then
    run_cmd rm "$l_li_dst"
  fi

  run_cmd ln -s "$l_li_src" "$l_li_dst"
}

backup_item() {
  l_bi_src="$1"
  l_bi_dst_root="$2"
  l_bi_dst="${l_bi_dst_root}/${l_bi_src#$HOME/}"
  l_bi_dst_path=$(dirname "$l_bi_dst")

  if [ ! -d "${l_bi_dst_path}" ]; then
    run_cmd mkdir -p "${l_bi_dst_path}"
  fi

  run_cmd mv "$l_bi_src" "$l_bi_dst"
}

process_directory() {
  for l_pd_rel_src in "$1"/*; do
    [ -e "$l_pd_rel_src" ] || continue

    l_pd_item=$(basename "${l_pd_rel_src}")
    if [ "${l_pd_item}" != "${l_pd_item#_}" ]; then
      l_pd_item=".${l_pd_item#_}"
    fi

    if echo "$shared_dirs" | grep -qw "$l_pd_item"; then
      process_directory "${l_pd_rel_src}" "${2}${l_pd_item}/"
      continue
    fi

    l_pd_src=$(get_abs_path "${l_pd_rel_src}")
    l_pd_dst="${HOME}/${2}${l_pd_item}"

    link_item "${l_pd_src}" "${l_pd_dst}" "${bkppath}"
  done
}

bkppath="${HOME}/.dotfilesbkp-$(date +%Y-%m-%d-%H:%M:%S)"

if [ $# -lt 1 ]; then
  parse_error
elif ! echo "$systems" | grep -qw "$1"; then
  parse_error
fi

if [ "$2" = "-d" ]; then
  dry_run=true
fi

if ! [ $dry_run ]; then
  printf "This script will link the dotfiles in this repository to your home \
directory, replacing your current configuration. Files that are replaced will \
be backed up to %s\n\nDo you wish to continue? (Y/n)" "${bkppath}"

  read proceed
  case "$proceed" in
    [Yy]*)
      ;;
    *)
      printf "Aborting\n"
      exit 0
      ;;
  esac
fi

cd $(dirname "$0")

install_dirs="common $1"

for dir in $install_dirs; do
  root="./${dir}/home"
  process_directory "$root" ""
done

printf "\nCompleted configuration for %s\n" "${1}"
if [ $dry_run ]; then
  printf "The -d option was used, so no changes have been made to the filesystem\n"
fi
