#!/bin/sh

# Check supplied directory and change to it
if [ $# -lt 1 ]; then
	echo "Error: Not enough arguments. Must provide a directory name."
	exit 1
fi

cd $1

# Avoid potentially disastrous results if the cd fails
if [ $? -ne 0 ]; then
	echo "Error: could not change to provided directory. Stopping..."
	exit 1
fi

# Avoid potentially disastrous results if tmp already exists
if [ -d tmp ]; then
	echo "Error: ${PWD}/tmp already exists. Stopping..."
	exit 1
fi

# Convert FLAC files to WAVE and use LAC to check them
mkdir tmp
for i in *.flac; do ffmpeg -i "$i" "tmp/$i.wav"; done
for i in tmp/*.wav; do lac "$i"; done

# Cleanup
rm -r ./tmp

echo "Test complete!"
