# pilonsi's .cshrc file

# csh config
# Enable tab autocompletion
set autolist ambiguous

# Aliases
alias ll 'ls -l'
alias hg 'history | grep'
alias marker 'source ~/bin/marker'

# History
set history=200

# Prompt
set prompt="%~ > "

# Load environment-specific settings
source ~/.cshrc.env
