# pilonsi's .cshrc file

# csh config
# Enable tab autocompletion
set autolist ambiguous

# Aliases
alias ll 'ls -l'
alias hg 'history | grep'
alias marker 'source ~/.local/bin/marker'

# Source environment specific aliases
source ~/.cshrc.env

# Keybindings
# Better autocomplete
bindkey "\e[A" history-search-backward
bindkey "\e[B" history-search-forward
bindkey "\eOA" history-search-backward
bindkey "\eOB" history-search-forward

# History
set history=200

# Colors!
set     red="%{\e[1;31m%}"
set   green="%{\e[1;32m%}"
set  yellow="%{\e[1;33m%}"
set    blue="%{\e[1;34m%}"
set magenta="%{\e[1;35m%}"
set    cyan="%{\e[1;36m%}"
set   white="%{\e[0;37m%}"
set     end="%{\e[0m%}"

# Prompt
set prompt="%~ > "

# Load environment-specific settings
source ~/.cshrc.env

# Clean up after ourselves...
unset red green yellow blue magenta cyan yellow white end
