" Pilonsi's .vimrc

" Colors
syntax on
set background=dark
colorscheme pencil
hi CursorLine cterm=NONE ctermbg=8
hi CursorLine cterm=NONE ctermbg=8

" Formatting
set tabstop=2
set softtabstop=2
set wrap!

" UI
set number
set ruler
set showcmd
set cursorline
set showmatch
set incsearch
set hlsearch
set wildmenu

" File handling
filetype plugin on

" Disable annoying mouse controls
set mouse=
set ttymouse=

" ADI Specific
set t_BE=                      " Fixes issues with copy/paste
set backspace=indent,eol,start " Fixes issue with delete/backspace
