" Basic settings
syntax on
colorscheme vacme
set background=light
hi CursorLine cterm=NONE ctermbg=8
hi CursorLine cterm=NONE ctermbg=8
set number
set ruler
set showcmd
set cursorline
set showmatch
set incsearch
set hlsearch
set wrap!

set wildmenu

set tabstop=2
set softtabstop=2
set expandtab

" ADI Specific
set t_BE=                      " Fixes issues with copy/paste
set backspace=indent,eol,start " Fixes issue with delete/backspace
