" Pilonsi's .vimrc

" Colors
syntax on
set background=dark
set colorcolumn=80
let g:pencil_terminal_italics = 0
let g:pencil_higher_contrast_ui = 1
colorscheme pencil

" gui vs cterm
set notermguicolors

" Formatting
set tabstop=2
set softtabstop=2
set wrap!

" UI
set number
set ruler
set showcmd
set cursorline
set showmatch
set incsearch
set hlsearch
set wildmenu

" File handling
filetype plugin on

" Disable annoying mouse controls
set mouse=
set ttymouse=

" Disable annoying auto comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" ADI Specific
set t_BE=                      " Fixes issues with copy/paste
set backspace=indent,eol,start " Fixes issue with delete/backspace

" Load environment specific settings
source ~/.vimrc.env
